import { StyleSheet } from 'react-native';

export const homeStyle = StyleSheet.create({
  container:    { flex: 1, padding: 10, backgroundColor: '#F5F5F5' },
  title:        { fontSize: 22, fontWeight: 'bold', marginBottom: 8 },
  loader:       { marginTop: 40 },
  errorText:    { color: 'red', textAlign: 'center', marginTop: 20 },
  cartBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fff',
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  cartBarText:   { fontSize: 13, fontWeight: '600', color: '#111' },
  cartBarTotal:  { fontSize: 12, color: '#3D5AFE', fontWeight: '700' },
  cartBarButton: {
    backgroundColor: '#3D5AFE',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
  },
  cartBarButtonText: { color: '#fff', fontWeight: '700', fontSize: 14 },
});

export const cardStyle = StyleSheet.create({
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    marginVertical: 5,
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    padding: 10,
  },
  image:     { width: 88, height: 88, borderRadius: 10, marginRight: 14, backgroundColor: '#eee' },
  category:  { fontSize: 11, fontWeight: '700', color: '#3D5AFE', textTransform: 'uppercase', letterSpacing: 0.5 },
  name:      { fontSize: 15, fontWeight: '700', color: '#111', marginTop: 3 },
  price:     { fontSize: 15, fontWeight: '800', color: '#3D5AFE', marginTop: 5 },
});

export const detailStyle = StyleSheet.create({
  container:   { padding: 20, backgroundColor: '#F5F5F5' },
  image: {
    width: '100%',
    height: 260,
    borderRadius: 20,
    marginBottom: 20,
    backgroundColor: '#eee',
  },
  name:        { fontSize: 24, fontWeight: '800', color: '#111', marginBottom: 10 },
  categoryChip: {
    alignSelf: 'flex-start',
    backgroundColor: '#E8EAFD',
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 999,
    marginBottom: 12,
  },
  categoryText: { fontSize: 13, fontWeight: '600', color: '#3D5AFE' },
  price:        { fontSize: 28, fontWeight: '800', color: '#3D5AFE', marginBottom: 16 },
  subtitle:     { fontSize: 13, fontWeight: '700', color: '#6B7280', letterSpacing: 0.8, textTransform: 'uppercase', marginBottom: 6 },
  description:  { fontSize: 15, color: '#6B7280', lineHeight: 22 },
  footer: {
    backgroundColor: '#fff',
    padding: 16,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  addButton: {
    backgroundColor: '#3D5AFE',
    borderRadius: 999,
    paddingVertical: 16,
    alignItems: 'center',
  },
  addButtonText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  loader:       { flex: 1, justifyContent: 'center', alignItems: 'center' },
});

export const cartStyle = StyleSheet.create({
  container:    { flex: 1, backgroundColor: '#F5F5F5' },
  listContent:  { padding: 10, paddingBottom: 20 },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginVertical: 5,
    flexDirection: 'row',
    alignItems: 'flex-start',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
    padding: 10,
  },
  image:       { width: 80, height: 90, borderRadius: 10, marginRight: 12, backgroundColor: '#eee' },
  name:        { fontSize: 14, fontWeight: '700', color: '#111', flex: 1 },
  price:       { fontSize: 13, fontWeight: '700', color: '#3D5AFE', marginTop: 3 },
  deleteBtn:   { padding: 4 },
  stepper:     { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F3F4F6', borderRadius: 999, marginTop: 8, alignSelf: 'flex-start' },
  stepBtn:     { paddingHorizontal: 12, paddingVertical: 4 },
  stepText:    { fontSize: 18, fontWeight: '600', color: '#3D5AFE' },
  qty:         { fontSize: 15, fontWeight: '800', color: '#111', minWidth: 24, textAlign: 'center' },
  subtotalLabel: { fontSize: 11, color: '#6B7280', marginTop: 8 },
  subtotal:    { fontSize: 14, fontWeight: '800', color: '#3D5AFE' },
  summaryCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    margin: 10,
    padding: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 4,
  },
  summaryRow:  { flexDirection: 'row', alignItems: 'center', marginVertical: 4 },
  summaryIcon: { fontSize: 20, marginRight: 10 },
  summaryLabel:{ flex: 1, fontSize: 14, color: '#6B7280' },
  summaryValue:{ fontSize: 16, fontWeight: '800', color: '#3D5AFE' },
  totalLabel:  { flex: 1, fontSize: 15, fontWeight: '600', color: '#111' },
  totalValue:  { fontSize: 20, fontWeight: '800', color: '#3D5AFE' },
  divider:     { height: 1, backgroundColor: '#E5E7EB', marginVertical: 10 },
  footer:      { padding: 16, paddingBottom: 28, backgroundColor: '#fff', borderTopWidth: 1, borderTopColor: '#E5E7EB', gap: 10 },
  confirmBtn:  { backgroundColor: '#3D5AFE', borderRadius: 999, paddingVertical: 16, alignItems: 'center' },
  confirmText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  clearBtn:    { borderWidth: 1.5, borderColor: '#3D5AFE', borderRadius: 999, paddingVertical: 14, alignItems: 'center' },
  clearText:   { color: '#3D5AFE', fontSize: 15, fontWeight: '700' },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
  emptyIcon:   { fontSize: 64, marginBottom: 16 },
  emptyTitle:  { fontSize: 20, fontWeight: '800', color: '#111' },
  emptySubtitle:{ fontSize: 14, color: '#6B7280', marginTop: 6 },
});
